import HomePage from "@frontEnd/container/HomePage";
import Head from "next/head";
import { getAllEvents } from "@frontEnd/api";

const AllEvents = ({ events }) => {
  console.log(events);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
};

export async function getStaticProps(context) {
  const response = await fetch(
    "https://next-ssr-1c859-default-rtdb.firebaseio.com/events.json"
  );
  const data = await response.json();
  const events = [];
  for (const key in data) {
    events.push({
      id: key,
      ...data[key],
    });
  }
  console.log("data : ", events);

  return {
    props: {
      events: events,
      fallback: false,
      revalidate: 1800,
      // wrap the returned object in an array
    },
  };
}

export default AllEvents;
