
import { getAllEvents } from "@frontEnd/api";
import { HomePage } from "@frontEnd/container/HomePage";
import Head from "next/head";

const AllEvents = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage eventList={props.events} />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const res = await getAllEvents();

  return {
    props: {
      events: res,
    },
  };
}

export default AllEvents;
